'use client';

import { useState } from 'react';
import {
  Card,
  CardContent,
  Typography,
  Button,
  Box,
  Tabs,
  Tab,
  Chip,
  Grid,
} from '@mui/material';
import { FileText, Plus } from 'lucide-react';
import type { Specification, SpecType } from '@/lib/types';

export default function SpecificationsPage() {
  const [specifications] = useState<Specification[]>([]);
  const [activeTab, setActiveTab] = useState<SpecType | 'ALL'>('ALL');

  const specTypes: (SpecType | 'ALL')[] = ['ALL', 'ANALYSIS', 'FIXES', 'PLANS', 'REVIEWS'];

  const filteredSpecs = activeTab === 'ALL' 
    ? specifications 
    : specifications.filter(spec => spec.type === activeTab);

  const getSpecColor = (type: SpecType) => {
    switch (type) {
      case 'ANALYSIS':
        return 'rgb(59 130 246)';
      case 'FIXES':
        return 'rgb(239 68 68)';
      case 'PLANS':
        return 'rgb(34 197 94)';
      case 'REVIEWS':
        return 'rgb(168 85 247)';
    }
  };

  return (
    <div className="space-y-6">
      <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <div>
          <Typography variant="h4" component="h1" sx={{ fontWeight: 700, color: 'rgb(250 250 250)', mb: 1 }}>
            Specifications
          </Typography>
          <Typography variant="body1" sx={{ color: 'rgb(161 161 170)' }}>
            Manage specification documents generated by Claude CLI
          </Typography>
        </div>
        <Button
          variant="contained"
          startIcon={<Plus size={20} />}
          sx={{
            backgroundColor: 'rgb(244 63 94)',
            '&:hover': { backgroundColor: 'rgb(225 29 72)' },
            textTransform: 'none',
            fontWeight: 600,
          }}
        >
          New Specification
        </Button>
      </Box>

      <Card
        sx={{
          backgroundColor: 'rgb(39 39 42)',
          border: '1px solid rgb(63 63 70)',
        }}
      >
        <Tabs
          value={activeTab}
          onChange={(_, newValue) => setActiveTab(newValue)}
          sx={{
            borderBottom: '1px solid rgb(63 63 70)',
            '& .MuiTab-root': {
              color: 'rgb(161 161 170)',
              textTransform: 'none',
              fontWeight: 600,
              '&.Mui-selected': {
                color: 'rgb(244 63 94)',
              },
            },
            '& .MuiTabs-indicator': {
              backgroundColor: 'rgb(244 63 94)',
            },
          }}
        >
          {specTypes.map((type) => (
            <Tab key={type} label={type} value={type} />
          ))}
        </Tabs>
      </Card>

      {filteredSpecs.length === 0 ? (
        <Card
          sx={{
            backgroundColor: 'rgb(39 39 42)',
            border: '1px solid rgb(63 63 70)',
            textAlign: 'center',
            py: 8,
          }}
        >
          <CardContent>
            <FileText size={48} className="text-zinc-600 mx-auto mb-4" />
            <Typography variant="h6" sx={{ color: 'rgb(250 250 250)', mb: 2 }}>
              No specifications yet
            </Typography>
            <Typography variant="body2" sx={{ color: 'rgb(161 161 170)', mb: 3 }}>
              Create specifications to generate prompts for Claude CLI
            </Typography>
            <Button
              variant="contained"
              sx={{
                backgroundColor: 'rgb(244 63 94)',
                '&:hover': { backgroundColor: 'rgb(225 29 72)' },
                textTransform: 'none',
                fontWeight: 600,
              }}
            >
              Create Specification
            </Button>
          </CardContent>
        </Card>
      ) : (
        <Grid container spacing={3}>
          {filteredSpecs.map((spec) => (
            <Grid size={{ xs: 12, md: 6 }} key={spec.id}>
              <Card
                sx={{
                  backgroundColor: 'rgb(39 39 42)',
                  border: '1px solid rgb(63 63 70)',
                  '&:hover': {
                    borderColor: 'rgb(244 63 94)',
                  },
                  transition: 'border-color 0.2s',
                }}
              >
                <CardContent>
                  <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'start', mb: 2 }}>
                    <Typography variant="h6" sx={{ fontWeight: 600, color: 'rgb(250 250 250)' }}>
                      Specification #{spec.id}
                    </Typography>
                    <Chip
                      label={spec.type}
                      size="small"
                      sx={{
                        backgroundColor: getSpecColor(spec.type),
                        color: '#fff',
                        fontWeight: 600,
                      }}
                    />
                  </Box>
                  <Typography variant="body2" sx={{ color: 'rgb(161 161 170)', mb: 2 }}>
                    {spec.content.substring(0, 150)}...
                  </Typography>
                  <Box sx={{ display: 'flex', gap: 1 }}>
                    <Chip
                      label={`${spec.tickets.length} tickets`}
                      size="small"
                      sx={{
                        backgroundColor: 'rgb(24 24 27)',
                        color: 'rgb(161 161 170)',
                        border: '1px solid rgb(63 63 70)',
                      }}
                    />
                  </Box>
                </CardContent>
              </Card>
            </Grid>
          ))}
        </Grid>
      )}
    </div>
  );
}
